title: Malibu Resort Motel
email:
description:
url: localhost:4000
markdown: kramdown

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - README.md

collections:
  rooms:
    output: false


sass:
  style: compact # possible values: nested expanded compact compressed
